---
title: "Two-way Analysis of Counts"
author: "Johannes S. P. Doehl"
date: "2024-05-23"
output: pdf_document
---

~~~{=comment}
# Setup
~~~
```{r setup-two-way-mixed, echo = FALSE, include = FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, eval = TRUE, cache = TRUE, dev = "png", warning = FALSE, message = FALSE, fig.pos = "H", out.extra = "")
options(java.parameters = "-Xmx200000m")
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre-1.8') # Needed to get around loading error of rJava
```

```{r functions-for-two-way-mixed-analysis}
# NOTE: the time variable ("Time_point") is used to split the data, thus, the repeated measure aspect is lost for the one-way and pairwise analysis downstream of the two-way analysis

# Robust one-way ANOVA split by other variables (two-way)
t1waySplit <- function(Data, indVar, outerLev, model) {
  
  lapply(levels(Data[[outerLev]]), function(xx) {
      
    t1way(formula = as.formula(paste("Counts ~", indVar)), 
          data = Data[Data[[outerLev]] %in% xx,], 
          tr = 0.1,
          error = model) %>%
      append(., split(.$effsize_ci, 
                      f = c("effsize_ci_lower", "effsize_ci_upper")), 
             after = 5) %>%
      .[!names(.) %in% c("effsize_ci", "alpha", "call")]
  }) %>%
    setNames(levels(Data[[outerLev]])) %>%
    lapply(., function(ww) {
      bind_cols(ww[!names(ww) %in% "call"])
    }) %>%
    bind_rows(., .id = outerLev) %>%
    # adjust_pvalue(method = "BH") %>%
    mutate(., "Sig." = symnum(.$p.value,
                              cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                              symbols = c("****", "***", "**", "*", "+", "ns")))
}
#-------------------------------------------------------------------------------

# Linear contrast expression split by other variables (two-way)
linconSplit <- function(Data, indVar, outerLev) {
  
  lapply(levels(Data[[outerLev]]), function(xx) {
    
    lincon(formula = as.formula(paste("Counts ~", indVar)), 
           data = Data[Data[[outerLev]] %in% xx,], 
           tr = 0.1,
           method = "BH") %>%
      capture.output(.) %>%
      trimws(.) %>%
      strsplit(., " ") %>%
      lapply(., function(yy) {
        
        yy[yy != ""]
      }) %>%
      .[c(6:9)] %>%
      lapply(., function(zz) {
        
        zz %>%
          as.data.frame(.) %>%
          t(.) %>%
          as.data.frame(.)
      }) %>%
      bind_rows(.) %>%
      tibble::remove_rownames(.) %>%
      tibble::column_to_rownames(., var = "V1") %>%
      t(.) %>%
      as.data.frame(.) %>%
      tibble::remove_rownames(.) %>%
      mutate(., across(where(Hmisc::all.is.numeric), as.numeric))
  }) %>%
    purrr::set_names(levels(Data[[outerLev]])) %>%
    bind_rows(., .id = outerLev) %>%
    mutate(., "Sig." = symnum(.$p.value,
                              cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                              symbols = c("****", "***", "**", "*", "+", "ns")))
}
```

```{r collate-data-for-two-way-mixed-analysis-from-RawDat}
Dat2wM <- RawDat[names(RawDat) %like% "mix2"]

# Set reference to "WN"
Dat2wM <- lapply(Dat2wM, function(ww) {
  
  # Set factor references for analysis
  ww <- within(ww, Diet <- relevel(Diet, ref = "WN"))
  
})

# Split dataframe containing multiple tissue data into separate dataframes for analysis
Dat2wMSpt <- mapply(function(qq, rr) {
  
  if (nlevels(qq$Cell_type) > 1) {
    
    xxx <- split(qq, qq$Cell_type) %>%
      
      lapply(., function(ww) {
        
        droplevels(ww)
        })
    
    xxx %>%
      purrr::set_names(paste(rr, names(xxx), sep = " - "))
    
  } else {
    
    list(qq)
  }
}, qq = Dat2wM, rr = names(Dat2wM), SIMPLIFY = FALSE) %>%
  flatten(.)

# Introduce a small amount of variability into the Week_0 average weight that was used
Dat2wMSpt <- lapply(c(1:length(Dat2wMSpt)), function(zz) {
  
  # Get the average value that was used
  Mean2w <- Dat2wMSpt[[zz]] %>% 
    dplyr::filter(Time_point %in% "Week_0") %>%
    .[, "Weight_g"] %>%
    unique(.)
  
  # The number of times it was applied
  RowNum <- Dat2wMSpt[[zz]] %>% 
    dplyr::filter(Time_point %in% "Week_0") %>%
    nrow(.)
  
  # Set seed to make this process reproducible
  set.seed(234)
  
  # Generate an artificial dataset with set mean and a small SD
  WgtW0 <- rnorm(n = RowNum, mean = Mean2w, sd = 0.1)
  
  # Replace the values
  Dat2wMSpt[[zz]][Dat2wMSpt[[zz]]$Time_point %in% "Week_0", "Weight_g"] <- WgtW0
  
  # Round weights back to one decimal
  Dat2wMSpt[[zz]] %>%
    mutate(., across(Weight_g, ~ round(.x, 1)))
}) %>%
  purrr::set_names(names(Dat2wMSpt))
```

```{r two-way-mixed-analysis}
# Data analysis by two-way model
Res2wM <- lapply(Dat2wMSpt, function(bb) {
  
  # DATA PREPARATION
  ExpDat <- bb %>%
    dplyr::select(any_of(c("Mouse", "Diet", "Time_point", "Weight_g"))) %>%
    rename(any_of(c(Counts = "Weight_g"))) %>%
    mutate(., across(where(is.integer), as.numeric)) %>%
    droplevels(.) %>%
    mutate(across(where(is.character), as.factor))
  
    # Generate raw data backup
    ExpDat2 <- ExpDat
    
  
  # DATA VISUALIZATION by box plot
  DatDis1 <- ggplot(ExpDat , 
                    aes(x = Diet, y = Counts, fill = Time_point)) + 
    geom_boxplot()
    
  
  # SUMMARY STATISTICS
  SumStat <- ExpDat %>%
    group_by(Diet, Time_point) %>%
    get_summary_stats(Counts, type = "full")
  

# ASSUMPTION TESTING ###########################################################

  # 1. NORMALITY ---------------------------------------------------------------
  
  # Data normality check and transformation loop
  for (aa in 1:100) {
    
    # 1.1 Normality of groups (pre-transformation decision)
    NormUV <- ExpDat %>% 
      group_by(., across(any_of(c("Diet", "Time_point")))) %>%
      rstatix::shapiro_test(Counts) %>%
      mutate("Outcome" = ifelse(.$p <= 0.05, "sig.", "ns"))
      
      # Data visualization: QQ-plot
      QQplotUV <- ggpubr::ggqqplot(ExpDat, "Counts", ggtheme = theme_bw()) +
      facet_grid(Time_point ~ Diet,
                 scales = "free")
      
    
    # Skewness and kurtosis check by group (pre-transformation decision)
    SkeKur <- lapply(list(ExpDat), function(x) {
      
      Skew <- x %>%
        group_by(., across(any_of(c("Diet", "Time_point")))) %>%
        metan::skew(.)
      
        if (any(Skew$Counts > 1)) {
  
          SkewOut <- "Right skew"
          
        } else if (any(Skew$Counts < -1)) {
  
          SkewOut <- "Left skew"
          
        } else {
  
          SkewOut <- "No skew"
        }
      
        print(SkewOut)
        
        print(Skew, n = 102)
      
      Kurt <- x %>%
        group_by(., across(any_of(c("Diet", "Time_point")))) %>%
        metan::kurt(.)
        
        if (any(Kurt$Counts > 2)) {
  
          KurtOut <- "Leptokurtic"
          
        } else if (any(Kurt$Counts < -2)) {
  
          KurtOut <- "Platykurtic"
          
        } else {
  
          KurtOut <- "Mesokurtic"
        }
      
        print(KurtOut)
          
        print(Kurt, n = 102)
      
      list("Skewness: Result" = SkewOut,
           "Skewness: Data"   = Skew, 
           "Kurtosis: Result" = KurtOut,
           "Kurtosis: Data"   = Kurt)
      
    }) %>%
      purrr::flatten(.)
    
    
    # 2. OUTLIERS---------------------------------------------------------------
    # Calculation of outliers
    OutLierUV <- ExpDat %>% # Untransformed data
      group_by(., across(any_of(c("Diet", "Time_point")))) %>%
      identify_outliers(Counts) %>%
      .[, c(1:3, (ncol(.)-1):ncol(.))]
    
      # Box-plot for visual assessment of outliers
      DatDis2 <- ggplot(ExpDat,
                        aes(x = Diet, y = Counts, fill = Time_point)) +
        geom_boxplot()
      
    
    # 3. HOMOGENEITY OF VARIANCES-----------------------------------------------
    
    # Testing for homogeneity of variance between the groups of the between-subjects factors for each level of the within-subjects factors
    EquVar <- ExpDat %>% # If violated, transformation may resolve the issue, or a robust mixed ANOVA can be applied
      group_by(Time_point) %>%
      levene_test(Counts ~ Diet, 
                  data = .) %>%
        mutate(., "Sig." = symnum(.$p,
                              cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                              symbols = c("****", "***", "**", "*", "+", "ns")))
    
      
  # 4. HOMOGENEITY OF COVARIANCES---------------------------------------------
    
    # The Box’s M is highly sensitive, so unless p<0.001 and your sample sizes are unequal, ignore it.
    BoxM <- box_m(data = ExpDat[, "Counts", drop = FALSE], 
            group = ExpDat[, "Diet"])
    
  # 5. SPHERICITY-------------------------------------------------------------
  
    # Mauchly's test executed automatically within anova_test() function, if within-subjects factor has >2 levels. For two within-subjects factor levels, the sphericity assumption hold by default. Here, we only have two levels in the within-subjects factor: "Ticks_Placed"
    
    # Two-way Mixed ANOVA (standard) for Maulchy's test
    Spher <- rstatix::anova_test( # This version is suitable if there are no ouliers
        data = ExpDat, dv = Counts, wid = Mouse,
        between = Diet, within = Time_point
        ) # Greenhouse-Geisser sphericity correction automatically applied if Mauchly's test is significant (p<0.05)
  # RESULTS OF ASSUMPTION TESTING-----------------------------------------------
    
    # Assumption of Gaussian distribution  
    if (any(NormUV$p <= 0.05)) {
      ResNormUV <- "Univariate: Non-Guassian"
      print(ResNormUV)
    } else {
      ResNormUV <- "Univariate: Guassian"
      print(ResNormUV)
    }
      
      print(NormUV, n = 102)
        
      print(QQplotUV)
      
      
    # Assumption of no significant outliers
    if (dim(OutLierUV)[1] != 0) {
      ResOutUV <- paste0(dim(OutLierUV)[1], " ", 
                      paste(gsub( ".*\\.", "", names(OutLierUV %>% 
                                                       dplyr::select(where(~any(.x == TRUE)))))[c(2,1)] %>% 
                              .[!is.na(.)], collapse = " "),
                      "(s) found")
      print(ResOutUV)
    } else {
      ResOutUV <- "No outliers"
      print(ResOutUV)
    }
      
      print(DatDis1)
      
      print(DatDis2)
      
      print(OutLierUV, n = 500)
      
      
    # Assumption of equal variance
    if (any(EquVar$p <= 0.05)) {
      ResEquVar <- "Heterogenous variance"
      print(ResEquVar)
    } else {
      ResEquVar <- "Homogeneous variance"
      print(ResEquVar)
    }
      
      print(EquVar)
    
      
    # Assumption of equal covariance
    if (BoxM$p.value <= 0.001) {
      BoxMVar <- "Heterogenous covariance"
      print(BoxMVar)
    } else {
      BoxMVar <- "Homogeneous covariance"
      print(BoxMVar)
    }
      
      print(BoxM)
      
      print(Spher)
      
    
  # MAKE DECISION about data transformation ------------------------------------ 
  bb <- readline("Continue loop?
                 0 = Leave loop
                 1 = Standard Transformation
                 2 = LambertW Transformation
                 3 = Revert to raw data")
    
    # Data transformation loop
    if (bb == 0) { # leave the loop
      
      break
      
    } else if (bb == 1) { # Transform the data
      
      # DATA TRANSFORMATION 
      ExpDat <- DatTrans(ExpDat,
                         # Name all dependent variables
                         depVar = "Counts",
                         # Name all independent variables (predictors)
                         indVar = "Diet")
      
      # Separate transformation information into separate variable
      ResTrans <- ExpDat[["Transformation"]]
      
        print(ResTrans)
        
      # Convert transformed data back into a dataframe
      ExpDat <- ExpDat[!names(ExpDat) %in% "Transformation"] %>%
        purrr::flatten(.) %>%
        bind_cols(.) %>%
        as.data.frame(.)
      
    } else if (bb == 2) {
      
      # Choose to apply Lambert W or not
      ExpDat <- ModSkeKur(ExpDat,
                          # Name all dependent variables
                          depVar = "Counts",
                          # Name all independent variables (predictors)
                          indVar = "Diet", 
                          Type = "h")
      
      # Separate transformation information into separate variable
      ResTransSK <- ExpDat[["Transformation"]]
    
        print(ResTransSK)
      
      # Convert transformed data back into a dataframe
      ExpDat <- ExpDat[!names(ExpDat) %in% "Transformation"] %>%
        purrr::flatten(.) %>%
        as.data.frame(.)
      
    } else if (bb == 3) {
      
      # Revert to raw data in case transformation did not work out
      ExpDat <- ExpDat2
    }
  }
  
  # In case no transformation was executed  
  if (exists("ResTrans") == FALSE & exists("ResTransSK") == FALSE) {
    
    ResTrans <- "untransformed"
    print(ResTrans)
    
    ResTransSK <- "untransformed"
    print(ResTransSK)
    
  } else if (exists("ResTrans") == FALSE) {
    
    ResTrans <- "untransformed"
    print(ResTrans)
    
  } else if (exists("ResTransSK") == FALSE) {
    
    ResTransSK <- "untransformed"
    print(ResTransSK)
  }
  
  
  # ASSUMPTION TESTING FOR MIXED-EFFECT MODEL ##################################

    # Test model assumptions
    
      # 1. Linearity: Only applies to continuous covariates; if only categorical covariates are used, no need to test.
      
      # 2. Normal distribution of residuals: QQplot of residuals, Shapiro-Wilks test, skewness & kurtosis analysis.
      
      # 3. Homogeneity of Variance: plot model & Levene's test of residuals by group.
      
      # 4. Normality of random effect: Get the estimate of random effect (here, random intercepts), and check them as check the residual. But it is not efficient because you just have 7 random intercepts.
      
      # 5. Another assumption is the independent between subjects: no test 
     
    # --------------------------------------------------------------------------
    
    # Residual normality check and transformation loop
    for (zz in 1:100) {
      
      # ------------------------------------------------------------------------
      
      # Mixed-effect model
      Mod  <- nlme::lme(Counts ~ Diet * Time_point,
                        random = ~1|Mouse,
                        method = "ML",
                        data = ExpDat)
      
      
    # ------------------------------------------------------------------------
    
      # 2. Normality of model residuals
      
        # Shapiro-Wilks test of residuals
        NormRes <- shapiro_test(residuals(Mod)) %>% # Shapiro-Wilks test of model residuals
          mutate("Outcome" = ifelse(.$p.value <= 0.05, "sig.", "ns"))
        
          if (NormRes$p.value < 0.05) {
            
            ResNormRes <- "Residuals: Non-Guassian"
            print(ResNormRes)
            
          } else {
            
            ResNormRes <- "Residuals: Guassian"
            print(ResNormRes)
            
          }
        
          print(NormRes)
        
          # Data visualization: QQ-plot
          QQplotRes <- ggqqplot(residuals(Mod), 
                                ggtheme = theme_bw(),
                                scales = "free")

            print(QQplotRes)
        
        # Check for data skewness and kurtosis to verify Gaussian distribution of residuals
          
        SkeKurRes <- lapply(list(Mod), function(x) {
          
          # Assess skewness of model residuals
          SkewRes <- moments::skewness(residuals(x))
        
          if (SkewRes > 1) {
            
            SkewOutRes <- "Residuals: right skew"
            
          } else if (SkewRes < -1) {
            
            SkewOutRes <- "Residuals: left skew"
            
          } else {
            
            SkewOutRes <- "Residuals: no skew"
            
          }
          
            print(SkewOutRes)
            
            print(SkewRes)
            
          
          # Assess kurtosis of model residuals
          KurtRes <- moments::kurtosis(residuals(x)) - 3
          
          if (KurtRes > 2) {
            
            KurtOutRes <- "Residuals: leptokurtic"
            
          } else if (KurtRes < -2) {
            
            KurtOutRes <- "Residuals: platykurtic"
            
          } else {
            
            KurtOutRes <- "Residuals: mesokurtic"
            
          }
          
            print(KurtOutRes)
            
            print(KurtRes)
        
          c(list("Skewness" = SkewRes), list("Kurtosis" = KurtRes))
        
        }) %>%
          purrr::flatten(.)
          
            
    # ----------------------------------------------------------------------------
      
      # 3. Homogeneity of Variance
        
        # scale-location plot
        print(plot(Mod,
              sqrt(abs(resid(.))) ~ fitted(.),
              type = c("p","smooth"), 
              lwd = 3, 
              col.line = 1))
        
          EquVarPlotRes1 <- recordPlot()
          
        # fitted vs residual with smooth line added
        print(plot(Mod, 
              type = c("p","smooth"), 
              lwd = 3, 
              col.line = 1))
          
          EquVarPlotRes2 <- recordPlot()
          
          
    # ----------------------------------------------------------------------------
          
      # 4. Normality of random effect
      
        # Shapiro-Wilks test
        NormResRE <- shapiro_test(coef(Mod)[, "(Intercept)"]) # Check normal distribution of random effect intercepts
        
        print(NormResRE)
      
        if (NormResRE$p.value < 0.05) {
        
          ResNormResRE <- "Random Effect: non-Guassian"
          print(ResNormResRE)
          
        } else {
          
          ResNormResRE <- "Random Effect: Guassian"
          print(ResNormResRE)
          
        }
        
          # QQ-plot of model random effect intercepts
          QQResRE <- ggqqplot(coef(Mod)[, "(Intercept)"],
                              ggtheme = theme_bw(),
                              scales = "free")
          
            print(QQResRE)
      
          # Check for data skewness and kurtosis to verify Gaussian distribution of residuals
          
          SkeKurRE <- lapply(list(Mod), function(x) {
            
            # Assess skewness of model residuals
            SkewRE <- moments::skewness(coef(x)[, "(Intercept)"])
          
            if (SkewRE > 1) {
              
              SkewOutRE <- "Random Effect: right skew"
              
            } else if (SkewRE < -1) {
              
              SkewOutRE <- "Random Effect: left skew"
              
            } else {
              
              SkewOutRE <- "Random Effect: no skew"
              
            }
            
              print(SkewOutRE)
              
              print(SkewRE)
              
            
            # Assess kurtosis of model residuals
            KurtRE <- moments::kurtosis(coef(x)[, "(Intercept)"]) - 3
            
            if (KurtRE > 2) {
              
              KurtOutRE <- "Random Effect: leptokurtic"
              
            } else if (KurtRE < -2) {
              
              KurtOutRE <- "Random Effect: platykurtic"
              
            } else {
              
              KurtOutRE <- "Random Effect: mesokurtic"
              
            }
            
              print(KurtOutRE)
              
              print(KurtRE)
            
              
            c(list("Skewness" = SkewRE), list("Kurtosis" = KurtRE))
            
          }) %>%
            purrr::flatten(.)
          
      
    # ----------------------------------------------------------------------------      
    
    # Make decision about data transformation   
    bb <- readline("Continue loop?
                   0 = Leave loop
                   1 = Standard Transformation
                   2 = LambertW Transformation
                   3 = Revert to raw data")
      
      # Data transformation loop
      if (bb == 0) { # leave the loop
        
        break
        
      } else if (bb == 1) { # Transform the data
        
        # DATA TRANSFORMATION
        
        ExpDat <- DatTrans(ExpDat,
                           # Name all dependent variables
                           depVar = "Counts",
                           # Name all independent variables (predictors)
                           indVar = c("Diet", "Route"))
    
          # Separate transformation information into separate variable
          ResTransMod <- ExpDat[["Transformation"]]
        
            print(ResTransMod)
          
          # Convert transformed data back into a dataframe
          ExpDat <- ExpDat[!names(ExpDat) %in% "Transformation"] %>%
            purrr::flatten(.) %>%
            bind_cols(.) %>%
            as.data.frame(.)
        
      } else if (bb == 2) {
        
        # Choose to apply Lambert W or not
        ExpDat <- ModSkeKur(ExpDat,
                            # Name all dependent variables
                            depVar = "Counts",
                            # Name all independent variables (predictors)
                            indVar = c("Diet", "Route"), 
                            Type = "h")
      
          # Separate transformation information into separate variable
          ResTransModSK <- ExpDat[["Transformation"]]
          
            print(ResTransModSK)
          
          # Convert transformed data back into a dataframe
          ExpDat <- ExpDat[!names(ExpDat) %in% "Transformation"] %>%
            purrr::flatten(.) %>%
            as.data.frame(.)
        
      } else if (bb == 3) {
        
        # Revert to raw data in case transformation did not work out
        ExpDat <- ExpDat2
      
      } else {
        
        print("Wrong input")
        stop()
      }
    }
      
    # In case no transformation was executed  
    if (exists("ResTransMod") == FALSE & exists("ResTransModSK") == FALSE) {
      
      ResTransMod <- "untransformed"
      print(ResTransMod)
      
      ResTransModSK <- "untransformed"
      print(ResTransModSK)
      
    } else if (exists("ResTransMod") == FALSE) {
      
      ResTransMod <- "untransformed"
      print(ResTransMod)
      
    } else if (exists("ResTransModSK") == FALSE) {
      
      ResTransModSK <- "untransformed"
      print(ResTransModSK)
    }
    
  
  # HYPOTHESIS TESTING SELECTION #############################################
  
  for (xx in 1:100) {
    
    # Make decision about data transformation   
    cc <- readline("Select statistical test to run based on assumption tests:
                    0 = Exist loop
                    1 = Standard two-way Mixed ANOVA
                    2 = Robust two-way Mixed ANOVA
                    3 = Linear mixed model")
    
    if (cc == 0) { # Leave the loop
      
      break
    
    } else if (cc == 1) { # Standard two-way ANOVA if assumptions are met
      
      # Two-way ANOVA
      res.aov2w <- rstatix::anova_test(data = ExpDat,
                                       dv = Counts,
                                       wid = Mouse,
                                       between = Diet,
                                       within = Time_point
                                       )
        
        ResAov2w <- "Standard two-way mixed ANOVA"
        print(ResAov2w)
        
        
        # One-way ANOVA for simple simple main effect
        res.aov1w <- ExpDat %>%
          group_by(Time_point) %>%
          rstatix::anova_test(data = .,
                              dv = Counts,
                              wid = Mouse,
                              between = Diet) %>%
          adjust_pvalue(method = "BH") %>%
          as.data.frame(.) %>%
          mutate(., "Sig." = symnum(.$p.adj,
                                    cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                                    symbols = c("****", "***", "**", "*", "+", "ns")))
          
          ResAov1w <- "Standard one-way ANOVA"
          print(ResAov1w)
        
          # Simple simple pairwise comparison
          res.aovPw <- ExpDat %>%
            group_by(Time_point, Route) %>%
            rstatix::pairwise_t_test(Counts ~ Diet,
                                     p.adjust.method = "BH")
            
            ResAovPW <- "Pairwise t test"
            print(ResAovPW)
      
    } else if (cc == 2) { # Robust two-way ANOVA
    
      # Three way ANOVA
      res.aov2w <- WRS2::t2way(Counts ~ Diet * Time_point,
                               id = Mouse,
                               data = ExpDat)
        
        ResAov2w <- "Robust two-way mixed ANOVA"
        print(ResAov2w)
        
        
        # One-way ANOVA for simple simple main effect
        res.aov1w <- t1waySplit(Data = ExpDat, 
                                indVar = "Diet", 
                                outerLev = "Time_point")
        
          ResAov1w <- "Robust one-way ANOVA"
          print(ResAov1w)
    
          # Simple simple pairwise comparison
          res.aovPw <- linconSplit(Data = ExpDat, 
                                   indVar = "Diet", 
                                   outerLev = "Time_point")
          
            ResAovPw <- "Linear contrast expression"
            print(ResAovPw)
    
    } else if (cc == 3) { # simple linear regression model
    
      # ANOVA to assess the significance of the independent variables
      res.aov2w <- nlme::anova.lme(Mod,
                                 type = "sequential",
                                 adjustSigma = FALSE)
      
      ResAov2w <- "Mixed effects model"
      print(ResAov2w) 
        
      # Post hoc by estimated marginal means
      PostHoc <- emmeans(Mod, ~ Diet * Time_point)
      
        # Individual sample effect and Pairwise comparison
        res.aovPw <- list("Estimated marginal means" = PostHoc,
          
          "Each level against overall level" = contrast(PostHoc,
                                                        method = "eff",
                                                        adjust = "sidak"),
          
          # Pairwise comparison
          "Pairwise comparison" = contrast(PostHoc,
                                           method = "pairwise",
                                           adjust = "sidak"),
          
          # Letter code for pairwise comparison
          "Pairwise letter code" = cld(PostHoc,
                                       alpha = 0.05,
                                       Letters = letters,      ### Use lower-case letters for .group
                                       adjust = "sidak")
        )
        
          ResAovPw <- "Estimated marginal means"
          print(ResAovPw)
        
        res.aov1w <- NA
        ResAov1w <- NA
    }
  }
      
  # COLLATE DATA----------------------------------------------------------------
    
  # Collate the test outcome calls
  AssTest <- as.data.frame(rbind("Dat_Transformation"                       = ResTrans,
                                 "Transformation_for_skewness_and_kurtosis" = ResTransSK,
                                 "Data_Normality_Assumption"                = ResNormUV,
                                 "Residual_Normality_Assumption"            = ResNormRes,
                                 "Outliers"                                 = ResOutUV,
                                 "Homogeneity_of_Variance"                  = ResEquVar,
                                 "2-way_analysis_applied"                   = ResAov2w,
                                 "1-way_analysis_applied"                   = ResAov1w,
                                 "Pairwise_analysis_applied"                = ResAovPw
                                 )) %>%
    setNames(., "Outcome")
  
  # Compile output data list
  AovDat <- list("Summary"                               = SumStat,
                 "Data Box plot (pre-transformed)"       = DatDis1,
                 "Assumption_Test_Outcome"               = AssTest,
                 "Data_Normality_Assumption"             = NormUV,
                 "QQ plot: by groups"                    = QQplotUV,
                 "Skewness and Kurtsosis"                = SkeKur,
                 "Residual_Normality_Assumption"         = NormRes,
                 "QQ plotof residuals"                   = QQplotRes,
                 "Residual_Normality_Assumption"         = SkeKurRes,
                 "Outliers"                              = OutLierUV,
                 "Data Box plot (post-transformed)"      = DatDis2,
                 "Homogeneity_of_Variance"               = EquVar,
                 "Random_Effect_Normality_Assumption"    = NormResRE,
                 "Random_Effect_Normality_Assumption"    = SkeKurRE,
                 "Scale location"                        = EquVarPlotRes1,
                 "Residuals_vs_Fitted"                   = EquVarPlotRes2,
                 "Box's M test"                          = BoxM,
                 "Spericity assumption"                  = Spher,
                 "Simple linear model"                   = Mod,
                 "2-way_ANOVA_post_hoc"                  = res.aov2w,
                 "1-way_ANOVA_simple_simple_main_effect" = res.aov1w,
                 "Pairwise_simple_simple_comparison"     = res.aovPw
                 )

}) %>%
  purrr::set_names(names(Dat2wMSpt))

gc()
```

